# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/brightcove/BrightcoveSpecs.git'

platform :ios, '8.0'
use_frameworks!

target 'brightcovevideoplayer' do
    pod 'Brightcove-Player-Core'
end

